server:
  port: 7878
spring:
  application:
    name: chat-service
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  data:
    mongodb:
      uri: mongodb://localhost:27017/chatdb
    redis:
      host: localhost
      port: 6379

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG

jwt:
  secret: 42244938548A0C2C0D9C78995F3A3430C17AB5B206C4DBF1E477A08E47119A99
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
