server:
  port: 7878
spring:
  application:
    name: chat-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/chatdb

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

